language: python
python:
- '2.7'
- '3.4'
- '3.5'
env:
- DJANGO="django>=1.9,<1.10"
install:
- pip install -r requirements/test.txt
- pip install coverage coveralls
- pip install $DJANGO
script:
- py.test tests --cov passwords
matrix:
  exclude:
after_success:
- coverage report
- coveralls
notifications:
  email:
    recipients:
    - tsamstag@securityinnovation.com
#deploy:
#  provider: pypi
#  user: maccesch
#  password:
#    secure: NoM2NEezIgizj/Q8JeezHKDDNzYsJCEBGIVJ3gAqSIhsq71hWBiA5coautBq214zIXR9P8WlX5ZzEvdEiZJc/u6jgL9Ggp2YOsi5fjGqbAdiGvlPd6lAfgnlbdNqJgjkTEckktiQEmiZYmZGz8tE57In7+BDIuxEg2QWX9eQ21E=
  on:
    tags: true
    repo: tecknicaltom/django-more-password-validators
